### ISSUE TITLE
Add context utils

### ISSUE THREAD

**Issue by kashifkhan0771** [kashifkhan0771/utils#1]
If we directly add a key to context with basic data type like string or int etc the linter give a warning. We should add a context utils which can help to add and retrieve values from context using key type or struct and avoid the linter issue `should not use basic type string as key in context.WithValue`.

**Comment by kashifkhan0771** [comment]
@shahzadhaider1 are you planning to implement this?

**Comment by kashifkhan0771** [comment]
@shahzadhaider1 are you planning to work on it? If you need any help or if you're tied up with something else, feel free to let me know!

**Comment by shahzadhaider1** [comment]
Thanks for the reminder. I have opened a pull request for this.
