### ISSUE TITLE
Advance String manipulation

### ISSUE THREAD

**Issue by kashifkhan0771** [kashifkhan0771/utils#12]
Add Functions to manipulate strings in ways that are not directly available in Go, such as:
- Reverse String
- Contains Any
- Common Prefix

**Note:** Any other functions can be added as well.

**Comment by abuzaforfagun** [comment]
I am interested on contributing to this issue.

**Comment by kashifkhan0771** [comment]
Thanks @abuzaforfagun for your interest! Feel free to take it on. While we don't have a detailed contribution guide at the moment, you can fork the repository and submit a pull request for this.

**Comment by kashifkhan0771** [comment]
If any function mentioned already exist, we can ignore it.
About the `commonPrefix` function, it should take in two or more strings and return the longest common prefix shared by them. Opposite to this `commonSuffix` can be implemented as well.

**Comment by kashifkhan0771** [comment]
Closing this issue as the PR associated is merged. If anyone want to add other string functions, please open a separate issue.
