### ISSUE TITLE
[FEATURE] random package (rand)

### ISSUE THREAD

**Issue by kashifkhan0771** [kashifkhan0771/utils#28]
## Feature Description

Add a new package for random generation (rand) which for now at least have following functions:
1. Random Number Generator <- generates any random number
2. Random Number Generator in range <- generate any random number between provided range
3. Random string Generator <- generate any random string
4. Random string generator with length <- generate any random string for provided length
---

## Use Case

If anyone requires a random number/string for testing or for any purpose this package should be able to provide that.
---

## Proposed Solution

N/A

---

## Pseudo Code

```go
// func names can be different if you have a more good names
func RandomInt() int {...}
func RandomRangeInt(from, to int) int {...}
func RandomString() string {...}
func RandomRangeString(length int) string {...}

**Comment by guisithos** [comment]
I am interested in developing this feature

**Comment by kashifkhan0771** [comment]
Thanks @guisithos. I am assigning this to you.
