### ISSUE TITLE
[FEATURE] URL utilities

### ISSUE THREAD

**Issue by kashifkhan0771** [kashifkhan0771/utils#35]
## Feature Description

Introduce a set of URL utility functions to simplify common URL operations in Go. This feature should provide helpers for URL parsing, encoding/decoding, building, validation, and manipulation, streamlining the process of handling URLs.

---

## Use Case

- Constructing and modifying URLs dynamically, such as appending query parameters based on user input or page states.
- Easily encoding parameters and constructing endpoints for REST API calls
- Validating incoming URLs to check for correct structure or to ensure they follow specific protocols

---

## Proposed Solution

Add a new package `url` or with any other name you think is more good. Add all the functions inside it with proper test cases.

---

## Additional Context

N/A

---

## Pseudo Code
Some functions that I have on top of my mind:
```go
func BuildURL(scheme, host, path string, query map[string]string) (string, error)
func AddQueryParams(urlStr string, params map[string]string) (string, error)
func IsValidURL(urlStr string, allowedSchemes []string) bool
func ExtractDomain(urlStr string) (string, error)
func GetQueryParam(urlStr, param string) (string, error)
// you can add more related to urls

**Comment by andremartinsds** [comment]
hey @kashifkhan0771 can you review this pr

**Comment by kashifkhan0771** [comment]
Reviewed and merged.

**Comment by kashifkhan0771** [comment]
Added in `v0.6.0`
