### ISSUE TITLE
[FEATURE] Fake Generator

### ISSUE THREAD

**Issue by kashifkhan0771** [kashifkhan0771/utils#73]
## Feature Description

Add a new utility functions in the fake package to generate some fake data like fake phone numbers, addresses etc to help users in the testing.

---

## Use Case

Fake data can be used during testing as well as can be used to fill the in-memory databases for mock testing.

---

## Proposed Solution

Simply add a new package `fake` and add relevant utility functions underneath. 

---

## Additional Context

N/A

---

## Pseudo Code
For now I have few functions on my mind but more can be added after discussion in the issue.
```go
func RandomPhoneNumber() string{}
func RandomAddress() string{}
func RandomUUID() string{}
func RandomDate() time.Time{}

**Comment by danilovict2** [comment]
I'd like to try

**Comment by kashifkhan0771** [comment]
Thanks @danilovict2 for the contribution!
